import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Sharp Digital Ireland - Premier Web Development Agency Dublin | React & Next.js Experts',
  description: 'Leading web development agency in Ireland specializing in React, Next.js, and custom digital solutions. Transform your business with expert web development services in Dublin and across Ireland.',
  keywords: 'web development Ireland, React development Dublin, Next.js developers Ireland, custom software development, digital agency Ireland, web design Dublin, full-stack development Ireland, JavaScript development, TypeScript development, UI/UX design Ireland, e-commerce development, mobile app development Ireland, digital transformation services, professional website design Dublin, responsive web design, SEO optimization Ireland, web application development, startup web development Ireland, enterprise web solutions',
  authors: [{ name: 'Sharp Digital Ireland', url: 'https://sharpdigital.ie' }],
  creator: 'Sharp Digital Ireland',
  publisher: 'Sharp Digital Ireland',
  category: 'Technology',
  classification: 'Web Development Agency',
  formatDetection: {
    email: false,
    address: false,
    telephone: false,
  },
  metadataBase: new URL('https://sharpdigital.ie'),
  alternates: {
    canonical: '/',
    languages: {
      'en-IE': '/',
      'en-GB': '/',
      'en-US': '/',
    },
  },
  openGraph: {
    title: 'Sharp Digital Ireland - Premier Web Development Agency Dublin',
    description: 'Leading web development agency in Ireland specializing in React, Next.js, and custom digital solutions. Expert developers serving Dublin and all of Ireland.',
    url: 'https://sharpdigital.ie',
    siteName: 'Sharp Digital Ireland',
    images: [
      {
        url: '/og-image.jpg',
        width: 1200,
        height: 630,
        alt: 'Sharp Digital Ireland - Web Development Agency Dublin',
        type: 'image/jpeg',
      },
      {
        url: '/og-image-square.jpg',
        width: 1200,
        height: 1200,
        alt: 'Sharp Digital Ireland Logo',
        type: 'image/jpeg',
      },
    ],
    locale: 'en_IE',
    type: 'website',
    countryName: 'Ireland',
  },
  twitter: {
    card: 'summary_large_image',
    site: '@sharpdigitalin',
    creator: '@sharpdigitalin',
    title: 'Sharp Digital Ireland - Premier Web Development Agency Dublin',
    description: 'Leading web development agency in Ireland. Expert React, Next.js & custom digital solutions.',
    images: ['/og-image.jpg'],
  },
  robots: {
    index: true,
    follow: true,
    nocache: false,
    googleBot: {
      index: true,
      follow: true,
      noimageindex: false,
      'max-video-preview': -1,
      'max-image-preview': 'large',
      'max-snippet': -1,
    },
  },
  verification: {
    google: 'your-google-verification-code',
    yandex: 'your-yandex-verification-code',
    yahoo: 'your-yahoo-verification-code',
    other: {
      'msvalidate.01': 'your-bing-verification-code',
    },
  },
  other: {
    'geo.region': 'IE-D',
    'geo.placename': 'Dublin, Ireland',
    'geo.position': '53.3498;-6.2603',
    'ICBM': '53.3498, -6.2603',
    'DC.title': 'Sharp Digital Ireland - Web Development Agency',
    'DC.creator': 'Sharp Digital Ireland',
    'DC.subject': 'Web Development, React, Next.js, Digital Solutions',
    'DC.description': 'Premier web development agency in Ireland specializing in modern web technologies',
    'DC.publisher': 'Sharp Digital Ireland',
    'DC.contributor': 'Sharp Digital Team',
    'DC.date': new Date().toISOString(),
    'DC.type': 'Service',
    'DC.format': 'text/html',
    'DC.identifier': 'https://sharpdigital.ie',
    'DC.language': 'en-IE',
    'DC.coverage': 'Ireland',
    'DC.rights': 'Copyright Sharp Digital Ireland',
  },
};